version: '3.7'

services:
  db:
    build: 
        context: .
        target: img_db
    restart: always
    ports: 
      - '${DBPORT}:3306'
    networks:
      - backend
    environment:
         POSTGRES_DB: ${POSTGRES_DB}
         POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'

  web:
    env_file:
      - var_for_api.txt 
    build: 
        context: .
        target: img_app
    networks: 
      - backend
    expose:
      - 8000
      - 5434
    ports:
      - "8080:8000"
    depends_on:
      - db
networks:
  backend:
    driver: bridge  
